### ISSUE TITLE
How to write models programmatically

### ISSUE THREAD

**Issue by eloualiche** [thorek1/MacroModelling.jl#26]
I am wondering how to use the macro to scale models up programmatically. 
What I have in mind is a model with multiple regions where most of the equations are the same for each region and could be recycled. 

In dynare this can be done with the dynare macro which allows for loops in building a mod file. 
I am sure it is possible to modify the expression in between `@model` and also `@parameters` but I tried using basic Meta.parse and could not get it to work.

Any pointer would be appreciated. 

Thank you.

**Comment by eloualiche** [comment]
This could work if we use vectors to represent the different regions. 
Something even more flexible (but I am not sure about practicality is to allow the macro to define new variables.

For example in dynare I would have the following code
```dynare
  @#for i in reg_idx
    [name='Demand for labor - region @{i}']
    L@{i} = 0
    @#for j in reg_idx
            +om@{i}_@{j}*L@{i}_@{j}
    @#endfor
    ;
   [name='Demand for capital - region @{i}']
    K@{i} = 0
    @#for j in reg_idx
            +om@{i}_@{j}*K@{i}_@{j}
    @#endfor
    ;
  @#endfor
```

Which after running the dynaremacro command evaluates as (`reg_idx = (1,2)` here):
```dynare
    [name='Demand for labor - region 1']
    L1 = 0
            +om1_1*L1_1
            +om1_2*L1_2
    ;
   [name='Demand for capital - region 1']
    K1 = 0
            +om1_1*K1_1
            +om1_2*K1_2
    ;
    [name='Demand for labor - region 2']
    L2 = 0
            +om2_1*L2_1
            +om2_2*L2_2
    ;
   [name='Demand for capital - region 2']
    K2 = 0
            +om2_1*K2_1
            +om2_2*K2_2
;
```

A work around would to generate a new model text file directly in julia which includes `@model  begin` on top. 
But this could be a useful addition.

**Comment by thorek1** [comment]
I would want to try to solve it within the @model block. let me try to come up with an intuitive syntax for your example. here is a proposal:

```
@model multi_country_model begin
    for c1 in [1,2]
        L(c1)[0] = for c2 in [1,2] + om(c1)(c2) * L(c1)(c2)[0] end
        
        K(c1)[0] = for c2 in [1,2] + om(c1)(c2) * K(c1)(c2)[0] end
    end
end
```

and then in the background (after it's implemented) he would translate this to:
```
L(1)[0] = om(1)(1) * L(1)(1)[0] + om(1)(2) * L(1)(2)[0]
K(1)[0] = om(1)(1) * K(1)(1)[0] + om(1)(2) * K(1)(2)[0]
L(2)[0] = om(2)(1) * L(2)(1)[0] + om(2)(2) * L(2)(2)[0]
K(2)[0] = om(2)(1) * K(2)(1)[0] + om(2)(2) * K(2)(2)[0]
```

I see that for full flexibility there is no way around `for` loops here. would that cover all possible use cases? 
also I am not sure about what braces to use. `(` is visually nice but can be confused with function calls. `{` makes it visually hard to read and `[` makes it hard to distinguish variable timing from country/sector/... indices. any views on syntax?

**Comment by eloualiche** [comment]
Thanks for pushing this and offering a solution. 
I am not quite sure about the syntax. 

I am personally in flavor of `{}` braces. Even if they do look clunky they differentiate strongly from function call `()` or array index `[]`. 

Regarding your proposal.
`L(idx)` (or `L{idx}`) would translate into `L(1)`.
I am wondering what would the variable name be down the road? Say in the irf or simulation DataFrame. 
I don't think it could be `L(1)`? 

So maybe it should translate from `L(idx)` to `L1` ?

But I will leave it up to you as you are running the code. If the function exists, I would be already very happy.

**Comment by thorek1** [comment]
hi Erik,

I finally took some time to implement programmatic model writing. I have a working version on the `multi_country` branch. Here is an example of how to use it:

```Julia

@model RBC_multi_country begin
    for co in [:H, :F]
        Y{co}[0] = ((LAMBDA{co}[0] * K{co}[-4]^theta{co} * N{co}[0]^(1-theta{co}))^(-nu{co}) + sigma{co} * Z{co}[-1]^(-nu{co}))^(-1/nu{co})

        K{co}[0] = (1-delta{co})*K{co}[-1] + S{co}[0]

        X{co}[0] = for lag in (-4+1):0 phi{co} * S{co}[lag] end

        A{co}[0] = (1-eta{co}) * A{co}[-1] + N{co}[0]

        L{co}[0] = 1 - alpha{co} * N{co}[0] - (1-alpha{co})*eta{co} * A{co}[-1]

        U{co}[0] = (C{co}[0]^mu{co}*L{co}[0]^(1-mu{co}))^gamma{co}

        psi{co} * mu{co} / C{co}[0]*U{co}[0] = LGM[0]

        psi{co} * (1-mu{co}) / L{co}[0] * U{co}[0] * (-alpha{co}) = - LGM[0] * (1-theta{co}) / N{co}[0] * (LAMBDA{co}[0] * K{co}[-4]^theta{co}*N{co}[0]^(1-theta{co}))^(-nu{co})*Y{co}[0]^(1+nu{co})

        for lag in 0:(4-1)  
            beta{co}^lag * LGM[lag]*phi{co}
        end +
        for lag in 1:4
            -beta{co}^lag * LGM[lag] * phi{co} * (1-delta{co})
        end = beta{co}^4 * LGM[+4] * theta{co} / K{co}[0] * (LAMBDA{co}[+4] * K{co}[0]^theta{co} * N{co}[+4]^(1-theta{co})) ^ (-nu{co})* Y{co}[+4]^(1+nu{co})

        LGM[0] = beta{co} * LGM[+1] * (1+sigma{co} * Z{co}[0]^(-nu{co}-1)*Y{co}[+1]^(1+nu{co}))

        NX{co}[0] = (Y{co}[0] - (C{co}[0] + X{co}[0] + Z{co}[0] - Z{co}[-1]))/Y{co}[0]
    end

    (LAMBDA{:H}[0]-1) = rho{:H}{:H}*(LAMBDA{:H}[-1]-1) + rho{:H}{:F}*(LAMBDA{:F}[-1]-1) + E{:H}[x]

    (LAMBDA{:F}[0]-1) = rho{:F}{:F}*(LAMBDA{:F}[-1]-1) + rho{:F}{:H}*(LAMBDA{:H}[-1]-1) + E{:F}[x]

    for co in [:H,:F] C{co}[0] + X{co}[0] + Z{co}[0] - Z{co}[-1] end = for co in [:H,:F] Y{co}[0] end
end

@parameters RBC_multi_country begin
    K[ss] = K_ss | beta
    K_ss = 10
    mu      =    0.34
    gamma   =    -1.0
    alpha   =    1
    eta     =    0.5
    theta   =    0.36
    nu      =    3
    sigma   =    0.01
    delta   =    0.025
    phi     =    1/4
    psi     =    0.5

    rho{:H}{:H} = 0.906
    rho{:F}{:F} = rho{:H}{:H}
    rho{:H}{:F} = 0.088
    rho{:F}{:H} = rho{:H}{:F}
end
```

any feedback is very welcome. 

I am ironing out some last issues and documentation and will merge it into the next release.

**Comment by eloualiche** [comment]
Thanks a lot. I will update my code and test this.

**Comment by thorek1** [comment]
I'll release a new version with this feature this week so you don't have to install from GitHub...

**Comment by RoshenSFernando** [comment]
Hi Thore,

Is it possible to declare arrays within the model block? For example, instead of **for co in [H, F]**, **Countries = [H,F]** and for **Countries**. 

For now, such arrays could not be declared outside the model block, as the elements are not separately defined. When I try declaring them within the model block, I get an error.

Cheers,

Roshen

**Comment by thorek1** [comment]
Hi roshen,

It's a limitation of julia macros that variables inside the macro don't have access to attached values.

I looked into what you are trying to do some time ago but didn't find a user friendly way of implementing it. I left it there but maybe there is a less user-friendly way: you could try write a function that writes the @model macro for you, fills it with the entries of Countries, and evaluates it.

**Comment by RoshenSFernando** [comment]
Thanks so much for the prompt response, Thorek! I've tried the method you suggested for some other languages (e.g., for converting a Dynare mod file for gEcon). I was expecting an internal fix within Julia. Since there doesn't seem to be any, I'll try and let you know if I succeed.
