### ISSUE TITLE
PyCall break down when parameters format differently

### ISSUE THREAD

**Issue by duzaichuan** [thorek1/MacroModelling.jl#31]
Hi Thore, thanks for this package!

I came across a weird breakdown when I formatted the parameters differently under a same model. I am on an Archlinux and using Julia 1.9.0 and the newset MacroModelling release.

@model BK1993_fig3 begin
    uc[0] = c[0]^-1
    ul[0] = θ_l * l[0]^-1
    y[0] = A * k[-1]^θ_k * n[0]^θ_n
    fk[0] = θ_k * A * k[-1]^(θ_k - 1) * n[0]^θ_n
    fn[0] = θ_n * A * k[-1]^θ_k * n[0]^(θ_n - 1)
    γ_x * k[0] = (1- δ_k) * k[-1] + iv[0]
    l[0] + n[0] = 1
    c[0] + iv[0] = (1 - τ) * y[0] + tr[0] + check_walras[0]
    c[0] + iv[0] + gb[0] = y[0]
    τ * y[0] = gb[0] + tr[0]
    uc[0] = λ[0]
    ul[0] = λ[0] * (1 - τ) * fn[0]
    β * λ[1] * (q[1] + 1 - δ_k) = γ_x * λ[0]
    q[0] = (1 - τ) * fk[0]
    gb[0] = GB_BAR + e_gb[x]
    1 + r[0] = γ_x * λ[0] / (λ[1] * β)
    w[0] = fn[0]
end

When I use the following simple parameter block, it works perfectly:

@parameters BK1993_fig3 begin
    A = 1.0
    γ_x = 1.016
    θ_k = 0.42
    θ_n = 1 - θ_k
    δ_k = 0.1
    β = 0.954
    τ = 0.2
    GB_BAR = 0.0667
    θ_l = 3.29
end

But when using a more detailed one, the julia session broke:

@parameters BK1993_fig3 begin
    A = 1.0
    γ_x = 1.016
    θ_k = 0.42
    θ_n = 1 - θ_k
    δ_k = 0.1
    N = 0.2
    L = 1 - N
    R = 0.065
    # β = 0.954
    β = γ_x / (1 + R)
    sG = 0.2
    τBAR = 0.2
    τ = 0.2
    Q = γ_x / β -1 + δ_k
    FK = Q/(1 - τBAR)
    K = (FK / ((θ_k * A * N^θ_n)))^(1 / (θ_k - 1))
    FN = θ_n * A * K^θ_k * N^(θ_n - 1)
    # W = FN
    IV = (γ_x - 1 + δ_k) * K
    Y = A * N^(1- θ_k) * K^θ_k
    GB_BAR = sG * Y
    # GB_BAR = 0.0667
    C = Y - IV - GB_BAR
    UC = C^(-1)
    UL = UC * (1 - τBAR) * FN
    θ_l = UL * L
    # θ_l = 3.29
end

The erros message:

`[4449] signal (11.1): Segmentation fault
in expression starting at none:1
unknown function (ip: 0x7f2edc436396)
unknown function (ip: 0x7f2edc4360fd)
macro expansion at /home/zach/.julia/packages/PyCall/twYvK/src/exception.jl:108 [inlined]
#107 at /home/zach/.julia/packages/PyCall/twYvK/src/pyfncall.jl:43 [inlined]
disable_sigint at ./c.jl:473 [inlined]
__pycall! at /home/zach/.julia/packages/PyCall/twYvK/src/pyfncall.jl:42 [inlined]
_pycall! at /home/zach/.julia/packages/PyCall/twYvK/src/pyfncall.jl:29
_pycall! at /home/zach/.julia/packages/PyCall/twYvK/src/pyfncall.jl:11 [inlined]
#_#114 at /home/zach/.julia/packages/PyCall/twYvK/src/pyfncall.jl:86 [inlined]
PyObject at /home/zach/.julia/packages/PyCall/twYvK/src/pyfncall.jl:86
unknown function (ip: 0x7f2f541b28e2)
_jl_invoke at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2940
+ at /home/zach/.julia/packages/SymPy/gkr7m/src/mathops.jl:9
+ at ./promotion.jl:410
unknown function (ip: 0x7f2f541b67f4)
_jl_invoke at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/julia.h:1879 [inlined]
do_call at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/interpreter.c:126
eval_value at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/interpreter.c:226
eval_stmt_value at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/interpreter.c:177 [inlined]
eval_body at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/interpreter.c:624
jl_interpret_toplevel_thunk at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/interpreter.c:762
jl_toplevel_eval_flex at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/toplevel.c:912
ijl_toplevel_eval_in at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/toplevel.c:971
eval at ./boot.jl:370 [inlined]
eval at /home/zach/.julia/packages/MacroModelling/HJvOI/src/MacroModelling.jl:1
jfptr_eval_10939 at /home/zach/.julia/compiled/v1.9/MacroModelling/NvgtF_QkPsA.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2940
@parameters at /home/zach/.julia/packages/MacroModelling/HJvOI/src/macros.jl:998
jl_invoke_julia_macro at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/ast.c:1036
jl_expand_macros at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/ast.c:1092
jl_expand_macros at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/ast.c:1135
ijl_expand_with_loc_warn at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/ast.c:1198
jl_toplevel_eval_flex at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/toplevel.c:709
jl_toplevel_eval_flex at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/toplevel.c:856
ijl_toplevel_eval_in at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/toplevel.c:971
eval at ./boot.jl:370 [inlined]
eval_user_input at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:153
repl_backend_loop at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:249
#start_repl_backend#46 at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:234
start_repl_backend at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:231
_jl_invoke at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2940
#run_repl#59 at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:379
run_repl at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/usr/share/julia/stdlib/v1.9/REPL/src/REPL.jl:365
jfptr_run_repl_60276.clone_1 at /home/zach/Julia/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2940
#1017 at ./client.jl:421
jfptr_YY.1017_32248.clone_1 at /home/zach/Julia/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/julia.h:1879 [inlined]
jl_f__call_latest at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/builtins.c:774
#invokelatest#2 at ./essentials.jl:816 [inlined]
invokelatest at ./essentials.jl:813 [inlined]
run_main_repl at ./client.jl:405
exec_options at ./client.jl:322
_start at ./client.jl:522
jfptr__start_37386.clone_1 at /home/zach/Julia/lib/julia/sys.so (unknown line)
_jl_invoke at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/julia.h:1879 [inlined]
true_main at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/jlapi.c:573
jl_repl_entrypoint at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/src/jlapi.c:717
main at /cache/build/default-amdci4-0/julialang/julia-release-1-dot-9/cli/loader_exe.c:59
unknown function (ip: 0x7f2f707fe84f)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
unknown function (ip: 0x401098)
Allocations: 64365407 (Pool: 64330036; Big: 35371); GC: 84`

**Comment by thorek1** [comment]
Hi,

thanks for posting this breakdown. Fortunately or unfortunately I cannot reproduce the bug. On my machine (Mac OS X) it works out of the box. Now I do have some suspicions where this might come from:
- what version of sympy (the python package not SymPy.jl) do you use?
- did you install Julia with a package manager or from the website / with juliaup?
I am not aware of issues related to sympy but I do know that Julia installations using the AUR package manager can fail.

I hope this helps.

**Comment by duzaichuan** [comment]
Thanks for the reply. I did use the Julia official bin download from the website and my python sympy is installed by pip and is the latest version 1.12.

I also tested on julia 1.9.1 just now, but the same bug.

**Comment by thorek1** [comment]
ok, I can recreate the bug on a linux machine.

I need to look more into it as to why this fails on linux: 
```
    # evaluate inputs where they are of the type: log(1/3) (no variables but need evaluation to becoe a Float64)
    for (i, v) in enumerate(calib_values_no_var)
        out = try eval(v) catch e end
```

as a short term fix try:
```
R = 1.065
β = γ_x * R^-1
```
this worked on linux for me.

**Comment by duzaichuan** [comment]
Thanks~ The fix also worked on my machine.

**Comment by duzaichuan** [comment]
> I need to look more into it as to why this fails on linux:
> 
> ```
>     # evaluate inputs where they are of the type: log(1/3) (no variables but need evaluation to becoe a Float64)
>     for (i, v) in enumerate(calib_values_no_var)
>         out = try eval(v) catch e end
> ```

I noticed in Julia doc that if try/catch is written in a single line, catch; is recommended instead of catch. [https://docs.julialang.org/en/v1/manual/control-flow/#Exception-Handling:~:text=Instead%2C%20use%20a%20semicolon%20or%20insert%20a%20line%20break%20after%20catch%3A](url)

Not sure whether this is relevant though.

**Comment by thorek1** [comment]
hi again, checkout the latest version: 0.1.25

I changed the way sympy is integrated, from PyCall to PythonCall. I tested the codes which previously failed and now they work on linux. 

I hope this helps

**Comment by duzaichuan** [comment]
Thanks!

**Comment by thorek1** [comment]
would you mind if I add the model to the tests and suite of implemented models? if yes, do you have the corresponding paper reference

**Comment by duzaichuan** [comment]
Yes, you can do it. The model is from Baxter and King (1993, AER): Macroeconomic Effects Of A Permanent Increase in Basic Government Purchases.
