### ISSUE TITLE
CI tests failing

### ISSUE THREAD

**Issue by gdalle** [thorek1/MacroModelling.jl#35]
Apparently it's because of a lack of memory

https://github.com/openjournals/joss-reviews/issues/5598#issuecomment-1610198924

I think #34 is a sign that there are unwanted memory leaks. Curious about the answer there.

**Comment by gdalle** [comment]
@thorek1 did you see this?

https://github.com/JuliaLang/julia/issues/39396#issuecomment-768456099

**Comment by thorek1** [comment]
I removed windows + Julia 1.8 from CI runs so now it passes. But I will dig deeper what was the cause there.
