### ISSUE TITLE
Clarify code example in paper

### ISSUE THREAD

**Issue by gdalle** [thorek1/MacroModelling.jl#49]
I think it would be nice (although not essential) to add comments to the RBC code example, saying what the variables and parameters stand for.

A few typos in this section:
- the "non-stochastic steady state" is first mentioned on line 22, so the acronym should go there
- a space is missing after `σ_z`
- on line 25 it is written "non-stochastic steady steady" -> if the acronym is introduced earlier, you can just say NSSS

https://github.com/openjournals/joss-reviews/issues/5598

**Comment by thorek1** [comment]
changed the NSSS mess and added more details on the model (let me know if it is clear enough to the non-econ reader)

**Comment by gdalle** [comment]
There are a few LaTeX display issues with unicode characters, and some sentences are a bit long (could use a comma), but otherwise this is an improvement indeed :)

**Comment by thorek1** [comment]
fixed unicode chars and had chatgpt help me with English

**Comment by gdalle** [comment]
All good! Gonna make a PR with the last few typos
