### ISSUE TITLE
Installation error at the latest Juila 1.10

### ISSUE THREAD

**Issue by duzaichuan** [thorek1/MacroModelling.jl#62]
Hi Thore,

As mentioned in the title, having trouble getting the package 0.1.32 installed in julia 1.10 on Archlinux.

> Error during loading of extension NLoptMathOptInterfaceExt of NLopt.
> InitError: Creating a new global in closed module `NLopt` (`Optimizer`) breaks incremental compilation because the side effects will not be permanent

**Comment by thorek1** [comment]
hi,

I didn't test on archlinux specifically but the GitHub tests with linux are working fine. I do get the same error on my personal Mac but I can use the package as normal anyway. I think this is an issue related to NLopt, but as it works for me and doesn't break the tests, I didn't investigate further.
how is it for you? if you just import the package (ignoring the error) and run your codes, does it work?

**Comment by duzaichuan** [comment]
Thanks. I was thinking that it was not build correctly, so did not import and test further. Yes, codes are running as expected in spite of the NLopt error.
