### ISSUE TITLE
Suggestion: Add dynare keyword to repo tags

### ISSUE THREAD

**Issue by duzaichuan** [thorek1/MacroModelling.jl#64]
Hi, 

I noticed a frustrating fact that this excellent toolkit is not found on the first page when googling "dynare Julia". Wondering if you consider adding a "dynare" tag to those on the repo front page, or some more dynare related descriptions?

Happy new year btw!

**Comment by thorek1** [comment]
happy new year! 

thank you for the feedback and I am glad to hear the package is useful to you. 

I have to think about your suggestion.
