### ISSUE TITLE
handling occasionally constraint

### ISSUE THREAD

**Issue by Aceampoma** [thorek1/MacroModelling.jl#71]
Hello Thore, Can you suggest how I handle this inequality, it's part of my equilibrium conditions; w[0] * N[0] ≤ ξ * q[0] * K[0]

this is how i handled it, but didn't work;
```Julia
@model G begin
    1 / c[0] = λ[0]
    
    θ*N[0]^χ = λ[0] * w[0]
    
    λ[0] = β *(λ[1] * (1 + r[0]))
    
    w[0] * (1 + μ[0]) = (1 - α) * A[0] * K[0]^α * N[0]^(1 - α)
    
    1 = q[0] * (1 - Φ* (I[0]/K[0] - δ))
    
    q[0] = (β * (λ[1] / λ[0])) * (α * A[1] * K[1]^(α - 1) * N[1]^(1 - α) + q[1] + Φ* (I[1]/K[1] + δ - 1)^2 / 2 - Φ* (I[1]/K[1] - δ) * (I[1]/K[1] + δ - 1) / 2)
    
    Y[0] = A[0] * (K[0]^α )* (N[0]^(1 - α))
    
    Y[0] = c[0] + I[0]
    
    K[1] = I[0] - Φ/2 * (I[0]/K[0] - δ)^2 + (1 - δ) * K[0]
    
    w[0]=max(w[0],ξ[0]*(q[0] * K[0])/ (N[0]))
    
    log(A[0]) = ρ * log(A[-1]) + σᵃ*A[x]
    
    log(ξ[0]) = (1 - ρᵋ) * log(ξ[ss]) + ρᵋ* log(ξ[-1]) + σᵋ*E[x]
    
    end
    
    @parameters G begin
    σᵃ= 0.01
    σᵋ= 0.01
    ρ= 0.98
    ρᵋ= 0.90
    δ = 0.02
    α = 0.33
    β = 0.99
    θ=7.71
    Φ=4.0
    χ=1.0
    
end

**Comment by thorek1** [comment]
can you post the (working) model and parameter block for the version without the occasionally binding constraint?

**Comment by Aceampoma** [comment]
I updated the earlier comment. This is the original model
![FC](https://github.com/thorek1/MacroModelling.jl/assets/142370455/9f566b5b-cb14-4494-b6dc-f933acb53adf)

**Comment by Aceampoma** [comment]
without the constraint;
@model G begin
    
    
    θ*N[0]^χ = 1/c[0] * w[0]
    
    1/c[0] = β *(1/c[1] * (1 + r[0]))
    
    #w[0] * (1 + μ[0]) = (1 - α) * A[0] * K[0]^α * N[0]^(1 - α)
    w[0] = (1 - α) * A[0] * K[0]^α * N[0]^(1 - α)
    
    1 = q[0] * (1 - Φ* (I[0]/K[0] - δ))
    
    q[0] = (β * (1/c[1] / 1/c[0])) * (α * A[1] * K[1]^(α - 1) * N[1]^(1 - α) + q[1] + Φ*(I[1]/K[1] + δ - 1)^2 / 2 - Φ*(I[1]/K[1] - δ)*(I[1]/K[1] + δ - 1) / 2)
    
    Y[0] = A[0] * (K[0]^α )* (N[0]^(1 - α))
    
    Y[0] = c[0] + I[0]
    
    K[1] = I[0] - Φ/2 *(I[0]/K[0] - δ)^2 + (1 - δ) * K[0]
    
    #w[0]=max(w[0],ξ[0]*(q[0] * K[0])/ (N[0]))
    
    log(A[0]) = ρ * log(A[-1]) + σᵃ*a[x]
    
    #log(ξ[0]) = (1 - ρᵋ) * log(ξ[ss]) + ρᵋ* log(ξ[-1]) + σᵋ*e[x]
    
    end
    
@parameters G begin
    σᵃ= 0.01
    #σᵋ= 0.01
    ρ= 0.98
    #ρᵋ= 0.90
    δ = 0.02
    α = 0.33
    β = 0.99
    θ=7.71
    Φ=4.0
    χ=1.0
    
end

**Comment by thorek1** [comment]
I didn't check myself with the code but my hunch is that this:

`w[0]=max(w[0],ξ[0]*(q[0] * K[0])/ (N[0]))` doesn't work

You need to define a second version of w which is used somewhere else in the model as well

**Comment by Aceampoma** [comment]
Okay. Thank you!
