### ISSUE TITLE
CondaPkg

### ISSUE THREAD

**Issue by gionikola** [thorek1/MacroModelling.jl#79]
Hello,

First off -- this package is incredible! I've been spreading the word. Thank you for the great work!

I'm dealing with a bizarre issue: I recently added and have been using MacroModeling.jl in a project. Since then, I've tried adding the package to other projects, and it's just not happening -- (1) The precompilation progress bar never completes; (2) As the package precompiles, it creates a .CondaPkg directory populated with about 200MBs worth of files (python dependencies?). Neither of these things happened in my first project. I have no clue what's going wrong.

I'm working on some time-sensitive stuff, so any help with this would be much appreciated.

**Comment by thorek1** [comment]
Hi Giorgi,

Glad to hear you find the package useful.

Could you give me some more details on the version you are trying to install?

It can happen that `add MacroModelling` does not install the latest version (something about the Julia package manager I don't fully understand yet). If that is the case, try `add MacroModelling@0.1.36`. Also what version of Julia re you using? I would recommend 1.10 onwards.

I hope this helps.
