### ISSUE TITLE
Macromodelling package issue

### ISSUE THREAD

**Issue by laurencejj** [thorek1/MacroModelling.jl#95]
Hi, I would love to use your package as it looks really useful. However, I am having issues getting it working, when I install it:

```
ERROR: LoadError: MethodError: no method matching AbstractDifferentiation.ForwardDiffBackend()
The type `AbstractDifferentiation.ForwardDiffBackend` exists, but no method is defined for this combination of argument types when trying to construct it.
```

I always get the following error:
`✗ ImplicitDifferentiation → ImplicitDifferentiationForwardDiffExt
`as your package is relying on ImplicitDifferentiation v0.5.2, however it is now at version 0.6.3 and even removing and installing the earlier package causes issues.

```
Error: Error during loading of extension ImplicitDifferentiationForwardDiffExt of ImplicitDifferentiation, use `Base.retry_load_extensions()` to retry.
│  │   exception =
│  │    1-element ExceptionStack:
```

and

```
ImplicitDifferentiation [57b37032] log:
 ├─possible versions are: 0.1.0 - 0.6.2 or uninstalled
 ├─restricted to versions * by project [7045c446], leaving only versions: 0.1.0 - 0.6.2
 │ └─project [7045c446] log:
 │   ├─possible versions are: 0.0.0 or uninstalled
 │   └─project [7045c446] is fixed to version 0.0.0
 ├─restricted to versions 0.6.2 by an explicit requirement, leaving only versions: 0.6.2
 └─restricted by compatibility requirements with MacroModelling [687ffad2] to versions: [0.2.0 - 0.3.0, 0.5.0 - 0.5.2] — no versions left
```

Please let me know how I can get it working! Thanks!!

**Comment by laurencejj** [comment]
I am also getting this behaviour when installing just the `MacroModelling` package in a clean temporary environment.

**Comment by laurencejj** [comment]
fixed by proper project package management

**Comment by thorek1** [comment]
Thanks for posting.

You should be able to safely ignore the precompilation error. I tested a fresh install and it works as intended despite the precompilation error. The upcoming release will fix the precompilation error.
